Feat/https (#11)
* feat(https): add nginx ssl config
* feat(https): generate ssl certs during install
* fix(https): put dhparam.pem in ssl/
* fix(install): source .env for correct output of domain/user
* feat(https): user port 8443
* feat(https): use PLACE_TLS for init container
* fix(nginx): fix cert path and remove deprecated ssl directive
* fix(install): check correct directory for cert
* fix(https): change ACA to PlaceOS
* feat(https): create cert for PLACE_DOMAIN
* fix(nginx): use https for X-Forwarded-Proto
* fix(user): change port in user description
* fix(user): change port in user descriptionUpdate install
* feat(restart): add cert check/create
* fix(nginx): try_files - change $uri to $uri/index.html

Authored-by: Viv Briffa <viv@place.tech>
Co-authored-by: Caspian Baska <caspianbaska@gmail.com>

diff --git a/restart b/restart
--- a/restart
+++ b/restart
@@ -51,9 +51,15 @@ do
   esac
 done
 
-PLACE_DOMAIN=${PLACE_DOMAIN:="localhost:8080"}
+source .env
+PLACE_DOMAIN=${PLACE_DOMAIN:="localhost:8443"}
 PLACE_EMAIL=${PLACE_EMAIL:="support@place.tech"}
 PLACE_PASSWORD=${PLACE_PASSWORD:="development"}
+
+if [ ! -f ./ssl/default-domain/fullchain.pem  ]; then
+    echo "=== Generating SSL certificates..."
+    ./scripts/generate-ssl ${PLACE_DOMAIN} 2> /dev/null || (printf "\nfailed to generate SSL certificates\n" && exit 1)
+fi
 
 echo "=== Refreshing services..."
 ./scripts/start-services ${SERVICES[@]} || (printf "\nfailed to start services\n" && exit 1)
